SELECT a.AUTHOR_ID, a.AUTHOR_NAME,  bb.CATEGORY,  SUM(bb.PRICE * bb.SALES) AS TOTAL_SALES
FROM (
         SELECT b.AUTHOR_ID, b.CATEGORY, bs.SALES, b.PRICE
         FROM BOOK_SALES bs INNER JOIN BOOK b ON bs.BOOK_ID = b.BOOK_ID
         WHERE bs.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
     ) bb INNER JOIN AUTHOR a ON bb.AUTHOR_ID = a.AUTHOR_ID
GROUP BY a.AUTHOR_ID, bb.CATEGORY
ORDER BY a.AUTHOR_ID, bb.CATEGORY DESC;
