SELECT BOOK_ID, Date_format(PUBLISHED_DATE,'%Y-%m-%d')PUBLISHED_DATE
from BOOK
where CATEGORY like '인문'and PUBLISHED_DATE like '2021%'
order by PUBLISHED_DATE

----------------
SELECT BOOK_ID, Date_format(PUBLISHED_DATE,'%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK
WHERE CATEGORY LIKE '인문'
  AND PUBLISHED_DATE BETWEEN '2021-01-01' AND '2021-12-31'
ORDER BY PUBLISHED_DATE;
