SELECT
    BOARD_ID,
    WRITER_ID,
    TITLE,
    PRICE,
    CASE
        WHEN USED_GOODS_BOARD.STATUS LIKE 'SALE' THEN '판매중'
        WHEN USED_GOODS_BOARD.STATUS LIKE 'RESERVED' THEN '예약중'
        WHEN USED_GOODS_BOARD.STATUS LIKE 'DONE' THEN '거래완료'
        ELSE USED_GOODS_BOARD.STATUS
        END AS STATUS
FROM
    USED_GOODS_BOARD
WHERE
    CREATED_DATE LIKE '2022-10-05'
ORDER BY
    BOARD_ID DESC;